### ISSUE TITLE
Can Audio be added too?

### ISSUE THREAD

**Issue by darkcheftar** [IanDesuyo/TkinterVideoPlayer#4]
@IanDesuyo The application is too good. But will it be possible to play the audio along with video too. 
That would be great to have.
Thanks In Advance

**Comment by IanDesuyo** [comment]
I tried to use pydub and simpleaudio to play the audio, but sometimes it doesn't sync with the video due to frame loop delay :(
I can provide the modified code if you don't mind.

**Comment by darkcheftar** [comment]
sure

**Comment by IanDesuyo** [comment]
Okay, I created a new branch [with-audio](https://github.com/IanDesuyo/TkinterVideoPlayer/tree/with-audio).
The code may have some bugs. If you can fix them, feel free to send me a PR :)
